---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: src/pages/projects
  label: Projects
  create: all
  match: "**/*"
- type: document
  path: src/pages/index.js
  label: Home
  read_only: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
